//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_img = new HashSet<product_img>();
        }
    
        public long product_id { get; set; }
        public string product_name { get; set; }
        public string product_des { get; set; }
        public Nullable<int> product_type { get; set; }
        public Nullable<int> product_new_type { get; set; }
        public Nullable<int> product_price_public { get; set; }
        public string product_photo { get; set; }
        public string product_photo2 { get; set; }
        public string product_content { get; set; }
        public string product_feature { get; set; }
        public string product_technical { get; set; }
        public string product_file { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> orderby { get; set; }
        public string lang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_img> product_img { get; set; }
    }
}
