//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public int id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<byte> is_hot { get; set; }
    }
}
